### ISSUE TITLE
where is the open-sora-plan code?

### ISSUE THREAD

**Issue by Edwardmark** [jjihwan/FIFO-Diffusion_public#11]
Thanks for your open-sourcing the code, but where is the open-sora-plan code?

**Comment by jjihwan** [comment]
For Open-Sora Plan, we are implementing parallel inference and other schedulers (e.g., PNDM scheduler). However, since I don't have much time to maintain this repository, it will take some time 🥲.

**Comment by pokameng** [comment]
@jjihwan 
hello，
I am integrating FIFO in Sora, can you provide some guidance?
THX！！！

**Comment by jjihwan** [comment]
@pokameng 
Hi, thank you for the waiting.
I'm trying to release the source code for open sora plan within 3~5 days.
If you want to implement yourself, please refer to VideoCrafter's code.

**Comment by pokameng** [comment]
@jjihwan 
hello ，I am integrating FIFO in[ Sora](https://github.com/hpcaitech/Open-Sora) rather than  open-sora-plan

**Comment by jjihwan** [comment]
Oh, I see. Since Open-Sora is also a DiT-based model like the Open-Sora Plan, I think you can refer to the code for the Open-Sora Plan once it is released.

You might need to re-implement:

1. timestep injection (different for each frame)
2. first-in, first-out queue for diagonal denoising in the main pipeline
3. latent partitioning and lookahead denoising

**Comment by pokameng** [comment]
> Oh, I see. Since Open-Sora is also a DiT-based model like the Open-Sora Plan, I think you can refer to the code for the Open-Sora Plan once it is released.
> 
> You might need to re-implement:
> 
> 1. timestep injection (different for each frame)
> 2. first-in, first-out queue for diagonal denoising in the main pipeline
> 3. latent partitioning and lookahead denoising

OKOK, look forward your codes releasing!!
