### ISSUE TITLE
Zeroscope

### ISSUE THREAD

**Issue by julkaztwittera** [jjihwan/FIFO-Diffusion_public#17]
Hi,
great work! I am really impressed by the length of videos you achieved.
May I ask when are you planning to release the Zeroscope version?

**Comment by jjihwan** [comment]
Thank you for your kind words!

Honestly, since the Zeroscope model does not perform well and is somewhat outdated compared to VideoCrafter2 and the Open-Sora plan, I am not planning to release the Zeroscope version at this time. However, if you need the code, please send me an email.
: kjh26720@snu.ac.kr

**Comment by 3019234115** [comment]
Could you send me the code of zeroscope? I just want to have a look at it as many works based on it.
My email is 1224432553@qq.com. Thank you so much!

**Comment by ZhangT-tech** [comment]
Hi may i also have the code for zeroscope? my email is 
tong.zhang.1@kaust.edu.sa
