### ISSUE TITLE
Support for Dyanmicraft

### ISSUE THREAD

**Issue by JACKHAHA363** [jjihwan/FIFO-Diffusion_public#18]
Dynamicraft is the img2video version of VideoCraft. How easy is it to extend current VideoCraft implementation?

**Comment by jjihwan** [comment]
FIFO-Diffusion is designed for T2V models, so I cannot assume how difficult it is to implement an I2V version of FIFO at this time. However, since DynamiCrafter is a model where the input image is not the first frame of the generated video, contrary to SV3D or other general I2V models, I believe it is not compatible with our method.
